name: Deploy Website
On:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run a sample script
        run: echo "Website code pushed successfully!"


