name: Welcome Workflow

on: [push]

jobs:
  welcome-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Say Hello
      run: echo "🎉 Welcome to GitHub Actions!"
